### PR TITLE
Build package only for Python 3.6 and 3.7

### PR DESCRIPTION
**Pull request by borchero**
# Motivation

Unfortunately, the mssql-scripter is dependent on `openssl=1.0` and Python >=3.8 depend on `openssl>=1.1`.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by borchero** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
That's unfortunate. This looks like a potentially good use case for condax.

**Comment by borchero** [comment]
@maresb which problem does it solve exactly? :smile: I didn't quite get it while briefly skimming through its docs

**Comment by maresb** [comment]
Suppose you're working on a project where you're using Python 3.11 but you want to be able to call mssql-scripter from the command line. You can't install it into your project environment due to the version conflict. But you could instead run `condax install mssql-scripter` and condax will set up a separate environment just for mssql-scripter and put the executable in your `PATH`.

**Comment by borchero** [comment]
@maresb I see, makes sense ;) I resorted to just create a second conda environment for my use case :smile:

**Pull request merged**
